### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by gulleh** [ksettaluri6/AutoCkt#1]
Hi,
I followed the steps to run the code. But I got the ValueError when running the
 run autockt/val_autobag_ray.py in the ipython.
ValueError: ('Observation outside expected value range', Box(15,), array([ 9.94010248e-03, -8.58339853e-01, -7.71450042e-01,  8.20714082e-01,
       -1.80438449e-01,  5.84788222e-01,  0.00000000e+00,  8.28439265e-01,
        3.30000000e+01,  3.30000000e+01,  3.30000000e+01,  3.30000000e+01,
        3.30000000e+01,  1.40000000e+01,  2.00000000e+01]))
Since I'm new to circuit design, I cannot understand the error. Could be the problem with ngspice?

**Comment by ksettaluri6** [comment]
My guess is that it has something to do with your NGSpice version. Did you follow the install from the link in the tutorial?

**Comment by gulleh** [comment]
Hi,
Thanks for the reply. My ngspice is the same version 27, however, I noticed the error is caused by wrong settings of the min/max of observation. I changed PERF_HIGH to 1 and another line high=np.array([TwoStageAmp.PERF_HIGH]*2*len(self.specs_id)+len(self.params_id)*[100])). It seems to work now. How can I check if these are the correct settings?

**Comment by ksettaluri6** [comment]
Hm interesting, so those lines are just used to let Gym know the size of the observation space. The value itself (PERF_HIGH=1) doesn't matter as I don't use it in the framework. So long as your code compiles, it should be working correctly.

**Comment by gulleh** [comment]
Thanks for the answer. I also observed similar plots as in the ones in the repo.

**Comment by MuzWong** [comment]
Hi , gulleh , i'm so sorry to disturb you.But i faced a tough problem showed below.When I do "run PPO --env opamp-v0 --num_val_specs 250 --traj_len 10000 --no-render",it occurs some error but i don't know how to solve it.In addition,what values should num_val_specs and traj_len take here? I just take them 250 and 10000.
`In [1]: run autockt/rollout.py /path/to/ray/checkpoint --run PPO --env opamp-v0 --num_val_specs 250 --traj_len 10000 --no-render

ModuleNotFoundError Traceback (most recent call last)
File ~/MuzWong/RL/AutoCkt/autockt/rollout.py:20, in
17 from ray.tune.registry import register_env
19 #from bag_deep_ckt.autockt.envs.bag_opamp_discrete import TwoStageAmp
---> 20 from envs.spectre_vanilla_opamp import TwoStageAmp
22 EXAMPLE_USAGE = """
23 Example Usage via RLlib CLI:
24 rllib rollout /tmp/ray/checkpoint_dir/checkpoint-0 --run DQN
(...)
29 --env CartPole-v0 --steps 1000000 --out rollouts.pkl
30 """
31 # Note: if you use any custom models or envs, register them here first, e.g.:
32 #
33 # ModelCatalog.register_custom_model("pa_model", ParametricActionsModel)
34 # register_env("pa_cartpole", lambda _: ParametricActionCartpole(10))

ModuleNotFoundError: No module named 'envs.spectre_vanilla_opamp''`
